language: java
# safelist
branches:
  only:
  - master
  - stage
  - dev
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

notifications:
  email: false
  irc:
    channels:
    - chat.freenode.net#skolarapp
    on_success: always
    on_failure: always
    use_notice: true
env:
  global:
  - secure: "YSVSLcH0c/VGLLc0GshhEqK4FybnLGsT2An0IOJa8tDa03CoLjhLHImNHHsigRQ5VtGzW77bDPB/DujG/F6JaBD6Ac8TiyFgkH3agoY2IDgtY++68959YEw8vT4pGu2H8FHC1EKn80xXI/eFF50ZFpNGXLp/Ve4U74gqJ2wPqGQVtCsZkzs8kGPvZ2+6f37St2kMeeCt3iq9jn/bJZrOzImcvZ4JYEKCbJ2wYgQHvAENrCFuAY3JYNsOUvP9wUB9LNWKeQNGaAezvlXi4Q88OIakZt4Gx56CrYPOJyxzCQiaAfpODbkT0bwSDFifslVCHEsZll2G2T3SmNkoK2V+ldqGqaJUUGKrRUnt/I85u4sfY6nmJQH9ZsSYqVbNzfFRvacggrdScZ17lV6k5GFPtdpL0+9OBnHqWMgpW/pnLAWt8YVW/JKx1XyR7crVlZT0DrMNZHUvOLhP7gI6SvDA9T3KnInZFcs3RvLeT3Rm86KfWbHbKl83gIIBpMXUcbYCy3FNfd8GY0wHJMpF+Gvby9v3MQ8nv488vTMDFDjnwGfGBE4dm6lMGNJ0zwh7MmPRNGi6W+6yGRkN4GGSRsXKbvCAUrISFP24TM+QCz/VK5zNZcfFtAlPpL+UtAYZE1pJXd3jcGCSAnRqzKb+2Sj5/XCnCQe0vJtGP6cPk/V35Ow="
os:
- linux

install:
- sudo apt-get install unzip;
- wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip && sudo unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/;

addons:
  chrome: stable


script: 
- ./gradlew stage
- ./gradlew test

after_success:
  - chmod a+x travisautomerge.bat
  - if [ "$TRAVIS_BRANCH" == "dev" ]; then
    echo "Merging dev into stage";
    BRANCHES_TO_MERGE_REGEX='dev' BRANCH_TO_MERGE_INTO=stage GITHUB_REPO=M3ttle/stringCalcWeb ./travisautomerge.bat;
    echo "All done, quitting now"; exit 0; fi

  - if [ "$TRAVIS_BRANCH" == "stage" ]; then
    echo "Merging stage into master";
    BRANCHES_TO_MERGE_REGEX='stage' BRANCH_TO_MERGE_INTO=master GITHUB_REPO=M3ttle/stringCalcWeb ./travisautomerge.bat; fi

