language: java
# safelist
branches:
  only:
  - master
  - stage
  - dev
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
  - MERGE_SCRIPT: "travisautomerge.bat"
  - GITHUB_REPO: "M3ttle/stringCalcWeb"
notifications:
  email: false
  irc:
    channels:
    - chat.freenode.net#skolarapp
    on_success: always
    on_failure: always
    use_notice: true
os:
- linux
#- osx
script: 
- ./gradlew stage

- 'if [ "$TRAVIS_BRANCH" == "dev" ]; then 
    echo "Mergaging dev into stage";
    chmod a+x travisautomerge.bat;
    BRANCHES_TO_MERGE_REGEX='dev' BRANCH_TO_MERGE_INTO=stage ./travisautomerge.bat;
    echo "All done, quitting now";
    exit 0;
  fi'

- 'if [ "$TRAVIS_BRANCH" == "stage" ]; then echo "stage branch"; fi'


#[[ $TRAVIS_PULL_REQUEST == “false” ]] && [[ $TRAVIS_BRANCH == “master” ]]